title: Glacier
description: Glacier is a type annotation extension to Java that enforces transitive class immutability.
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
